import ThemeApp from "@/components/styles/ThemeApp";
import NavBar from "@/components/navBar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "ApplicationHub App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeApp>
          <NavBar />
          {children}
          <Footer />
        </ThemeApp>
      </body>
    </html>
  );
}
