import ThemeApp from "@/components/styles/ThemeApp";

export const metadata = {
  title: "ApplicationHub App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeApp>
          {children}
        </ThemeApp>
      </body>
    </html>
  );
}
